### ISSUE TITLE
D-Net、Dynamic U-Net源码

### ISSUE THREAD

**Issue by xinxin5555555** [sotiraslab/SC-MIL#2]
您好，最近阅读了您的文献：Dynamic U-Net: Adaptively Calibrate Features
for Abdominal Multi-organ Segmentation、D-Net: Dynamic Large Kernel with Dynamic
Feature Fusion for Volumetric Medical Image
Segmentation受益匪浅，在阅读完文献后，想学习一下您的代码，但是没有找到，可不可以麻烦您分享一下链接？谢谢您！！

**Comment by peijieq** [comment]
Thank you very much for being interested in our latest work. I believe the source code of Dynamic U-Net, D-Net, and our recent Transformer-based segmentation models have been released: we kindly direct you to those repos https://github.com/sotiraslab/DLK, https://github.com/sotiraslab/DynamicUNet, https://github.com/sotiraslab/AgileFormer.
